=== BubblesOnWaterSurface/lcd4linux/documentation/dtd/references.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  DTD of documentation for the lcd4linux project
    Copyright 2004 Xavier Vello <xavier66@free.fr>
    Copyright 2004 The LCD4Linux Team <lcd4linux-devel@users.sourceforge.net>
-->

<!ENTITY l4l "LCD4Linux">
<!ENTITY L4L "LCD4Linux">

<!ELEMENT references (ref*)>

<!ELEMENT ref ((class|file|label|hiden))>
<!ATTLIST ref id CDATA #REQUIRED>
  <!ELEMENT class (#PCDATA)>
  <!ELEMENT file (#PCDATA)>
  <!ELEMENT label (#PCDATA)>
  <!ELEMENT hiden EMPTY>

=== BubblesOnWaterSurface/lcd4linux/documentation/data/references.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE references SYSTEM "../dtd/references.dtd">

<references>
<!--Pages about lcd4linux-->
  <ref id="index">
    <class/>
    <file>index</file>
    <label>Documentation index</label>
    <hiden/>
  </ref>
  <ref id="overview">
    <class/>
    <file>overview</file>
    <label>&L4L; overview</label>
  </ref>
  <ref id="bug_report">
    <class/>
    <file>bug_report</file>
    <label>How to report bugs or get support</label>
  </ref>
  <ref id="contact">
    <class/>
    <file>contact</file>
    <label>How to contact us</label>
  </ref>
  <ref id="write_doc">
    <class/>
    <file>write_doc</file>
    <label>How to write documentation</label>
  </ref>
  
  <ref id="test">
    <class/>
    <file>example</file>
    <label>A test page</label>
  </ref> 

<!--Drivers-->
  <ref id="drivers_index">
    <class>drivers</class>
    <file>index</file>
    <label>Drivers index</label>
    <hiden/>
  </ref>
  <ref id="hd44780">
    <class>drivers</class>
    <file>hd44780</file>
    <label>HD44780 displays driver</label>
  </ref>

<!--Plugins-->
  <ref id="plugins_index">
    <class>plugins</class>
    <file>index</file>
    <label>Plugins index</label>
    <hiden/>
  </ref>
  <ref id="i2c_sensors">
    <class>plugins</class>
    <file>i2c_sensors</file>
    <label>I2C sensors plugin</label>
  </ref>
  
</references>
